# -*- coding: utf-8 -*-
"""Yet another copy of Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1prrBVDMeoDePmDK5GV1_UTPxVJ8s7Oyb
"""

print("-----Student Data-----")
name=input("enter student name")
name=input("enter father name")
print("-----Marks-----")
maths=float(input("enter marks of math"))
computer=int(input("enter marks of computer"))
chemistry=int(input("enter marks of chemistry"))
physics=float(input("enter marks of physics"))
urdu=int(input("enter marks of urdo"))
total_marks=maths+computer+chemistry+physics+urdu
Percentage=(total_marks/500)*100
if Percentage  >=80:
     grade = 'A+'
elif Percentage  <=70:
     grade  ='A'
elif Percentage  <=60:
     grade = 'B'
elif Percentage <=50:
      grade = 'C'
elif Percentage  <= 40:
      grade = 'D'
else:
     grade = 'Fail'
print("\n------Marksheet------")
print("Student name",name)
print("father name", name)
print("maths",maths)
print("computer",computer)
print("chemistry",chemistry)
print("physics",physics)
print("urdu",urdu)
print("total_marks",total_marks)
print("percentage",Percentage)
print("Grade,grade")

